# Generated by Django 5.2.12 on 2026-03-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_seed_datos_reales'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
