# Generated by Django 5.2.12 on 2026-03-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_socio_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='dni',
        ),
    ]
